// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://temqwtiveojbzuhwkpcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbXF3dGl2ZW9qYnp1aHdrcGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4MjM2NjksImV4cCI6MjEwNTM5OTY2OX0.smDJOKnZ17fgth_4Ej8wD_Zt4JkRmQEOYE2pXeQ42ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});